FROM tomcat
RUN apt update && apt install -y git maven \
    && rm -rf /var /lib/apt/lists/*
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git \
    && cd boxfuse-sample-java-war-hello \
    && mvn package \
    && cd target \
    && cp hello-1.0.war /var/java_app/apache-tomcat-10.0.20/webapps