FROM maven
RUN apt update && apt install -y git
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git \
    && cd boxfuse-sample-java-war-hello \
    && mvn package \
    && cd target \
    && cp hello-1.0.war ../../webapps