FROM maven:3.6.3-jdk-11 AS BUILDER
WORKDIR /usr/share/maven
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git \
    && mv boxfuse-sample-java-war-hello/* /usr/share/maven
RUN mvn package
#FROM maven:3.6.3-jdk-11

#WORKDIR /app/boxfuse-sample-java-war-hello/
#RUN mvn clean package
#CMD ["java", "-jar", "target/*.jar"]

#RUN    mvn package && \
#       cp target/hello-1.0.war /var/lib/tomcat9/webapps/

FROM tomcat
#RUN pwd && ls
COPY --from=BUILDER /usr/share/maven/target/*.war /usr/local/tomcat/webapps