FROM ubuntu:18.04
RUN apt -y update && apt install -y default-jdk tomcat9 maven git && \
    git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git && \
    cd boxfuse-sample-java-war-hello && \
    mvn package && \
    cd target && \
    cp hello-1.0.war /var/lib/tomcat9/webapps/
EXPOSE 8080