version: '3.9'
services:
  build_service:
    build: .
    container_name: maven_build
    volumes:
      - db:/usr/share/maven/target
#    networks:
#      - boxfusenet

  prod_service:
    image: tomcat
    container_name: tomcat_prod
    depends_on:
      - build_service
#        condition: service_healthy
    ports:
      - "7776:8080"
    volumes:
      - db:/usr/local/tomcat/webapps
#    networks:
#      - boxfusenet

volumes:
  db:

#networks:
#  boxfusenet:
#    driver: bridge